name: bandits
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - pandas=3.0.1
  - numpy=1.26.4
  - scikit-learn=1.8.0
  - matplotlib
  - seaborn
  - xgboost
  - joblib=1.5.2
  - ipykernel
  - pip
  - pip:
      - torch==2.8.0
      - torchvision
      - torchaudio
      - loguru
      - google-genai