name: bandits
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - joblib
  - ipykernel
  - pip
  - pip:
      - torch==2.8.0
      - torchvision
      - torchaudio
      - loguru
      - google-genai